### ISSUE TITLE
Lose connection to RFID reader

### ISSUE THREAD

**Issue by AaronHuus** [ransford/sllurp#120]
I am communicating with my Zebra FX9500 RFID reader and running an inventory every second or so.  This works and is stable for a while (12 hours or so), but then inevitably the following error occurs.  Even when I try to reconnect I get the same error, I have to do some scans initated from the RFID reader Web UI to "reset" things and then it will work again.

```
Unhandled Error
2019-02-20 16:09:15 - INFO - lost connection: 1
Traceback (most recent call last):
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/twisted/protocols/basic.py", line 579, in dataReceived
    why = self.rawDataReceived(data)
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/sllurp/llrp.py", line 689, in rawDataReceived
    lmsg = LLRPMessage(msgbytes=data[:msg_len])
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/sllurp/llrp.py", line 43, in __init__
    self.deserialize()
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/sllurp/llrp.py", line 86, in deserialize
    name: dict(decoder(body))
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/sllurp/llrp_proto.py", line 683, in decode_ROAccessReport
    ret, data = decode('TagReportData')(data)
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/sllurp/llrp_proto.py", line 2592, in decode_TagReportData
    ret, nbytes = llrp_decoder.decode_tve_parameter(body)
  File "/Users/z003bhg/.virtualenvs/rfid/lib/python3.7/site-packages/sllurp/llrp_decoder.py", line 50, in decode_tve_parameter
    param_name, param_fmt = ext_param_formats[subtype]
builtins.KeyError: 1
```

Here is how I am setting up the reactor.

```
        factory: LLRPClientFactory = LLRPClientFactory(
            duration=settings.intentory_every_n_seconds,
            disconnect_when_done=True,
            antennas=tuple(settings.read_power.keys()),
            tx_power=settings.read_power,
            # antenna_dict=settings.read_power,
            session=0,
            tag_population=12,
            start_inventory=True,
            tag_content_selector={
                'EnableROSpecID': False,
                'EnableSpecIndex': False,
                'EnableInventoryParameterSpecID': False,
                'EnableAntennaID': True,
                'EnableChannelIndex': False,
                'EnablePeakRSSI': True,
                'EnableFirstSeenTimestamp': True,
                'EnableLastSeenTimestamp': True,
                'EnableTagSeenCount': False,
                'EnableAccessSpecID': False,
            }
        )
        factory.addTagReportCallback(tag_callback)
        reactor.connectTCP(settings.reader_device, LLRP_PORT, factory)
        rfid_thread = Thread(name='RFID Reader Thread', target=reactor.run, args=(False,))
        rfid_thread.setDaemon(True)
        rfid_thread.start()
```

Any initial thoughts? Thank you for the support

**Comment by ransford** [comment]
Thanks for providing a full traceback. A few starting points:
- In `llrp_proto.decode_TagReportData()`, wrap the call to `llrp_decoder.decode_tve_parameter()` in a `try`/`except`, and in the `except` block, dump the contents of `body` to a log message and paste the result here. Then we can try to unpack the data `decode_tve_parameter()` is failing to decode.
- Look up your reader's custom LLRP extensions to see what kind of parameter type `1` is. If you look at `llrp_decoder.py` you'll see that there are some Impinj-specific values in `ext_param_formats`.
