### ISSUE TITLE
Error in Deserializing: ERROR: Problem with READER_EVENT_NOTIFICATION message format

### ISSUE THREAD

**Issue by Buestue** [ransford/sllurp#160]
Hi Ben,

Im trying to read from a Kathrein Reader and got the Error. I think the problem is related to the Timestamp type of the message, which is 129 insetad of 128

data:  b'\x00\x81\x00\x0c\x00\x00\x00\x0b\x8bUU\xb1\x01\x00\x00\x06\x00\x00'
header:  b'\x00\x81\x00\x0c'
par_header:  !HH
msgtype:  129
Problem with READER_EVENT_NOTIFICATION message format
sllurp.llrp_errors.LLRPError: missing or invalid UTCTimestamp parameter
unexpected message None while connecting

attached is the logfile. I appreciate your help!
[issue2.txt](https://github.com/ransford/sllurp/files/6169585/issue2.txt)

2021-03-18 19:10:05,111 sllurp.cli: DEBUG: inventory args: Args(host=('192.168.178.48',), port=5084, time=None, every_n=None, antennas='1', tx_power=0, tari=0, session=2, population=4, mode_identifier=None, reconnect=False, tag_filter_mask=None, impinj_extended_configuration=False, impinj_search_mode=None, impinj_reports=False, impinj_fixed_freq=False)
2021-03-18 19:10:05,112 sllurp.verb.inventory: INFO: Antenna map: {'192.168.178.48': {'1': 'Antenna 1'}}
2021-03-18 19:10:05,115 sllurp.llrp: INFO: connecting to 192.168.178.48:5084...
2021-03-18 19:10:05,124 sllurp.llrp: DEBUG: Building protocol for 192.168.178.48:5084
2021-03-18 19:10:05,125 sllurp.llrp: DEBUG: Antennas in buildProtocol: [1]
2021-03-18 19:10:05,126 sllurp.llrp: DEBUG: 192.168.178.48:5084 start_inventory: True
2021-03-18 19:10:05,176 sllurp.llrp: INFO: will reset reader state on connect
2021-03-18 19:10:05,176 sllurp.llrp: INFO: will start inventory on connect
2021-03-18 19:10:05,179 sllurp.llrp: INFO: using antennas: [1]
2021-03-18 19:10:05,181 sllurp.llrp: INFO: transmit power: {1: 0}
2021-03-18 19:10:05,184 sllurp.llrp: INFO: connected to ('192.168.178.48', 5084) (192.168.178.48:5084)
2021-03-18 19:10:05,184 sllurp.llrp: DEBUG: got 32 bytes from reader: b'043f000000200000000000f600160081000c00000000da3c043d010000060000'
2021-03-18 19:10:05,188 sllurp.llrp: DEBUG: expect 32 bytes (have 32)
2021-03-18 19:10:05,191 sllurp.llrp: DEBUG: deserializing READER_EVENT_NOTIFICATION command
2021-03-18 19:10:05,259 sllurp.llrp_proto: DEBUG: decode_ReaderEventNotification
2021-03-18 19:10:05,265 sllurp.llrp_proto: DEBUG: decode_ReaderEventNotificationData (type=246 len=22)
2021-03-18 19:10:05,270 sllurp.llrp_proto: DEBUG: decode_UTCTimestamp
2021-03-18 19:10:05,271 sllurp.llrp: ERROR: Problem with READER_EVENT_NOTIFICATION message format
Traceback (most recent call last):
  File "c:\users\buestuen2\appdata\local\continuum\anaconda3\lib\site-packages\sllurp\llrp.py", line 85, in deserialize
    name: dict(decoder(body))
  File "c:\users\buestuen2\appdata\local\continuum\anaconda3\lib\site-packages\sllurp\llrp_proto.py", line 826, in decode_ReaderEventNotification
    ret, body = decode('ReaderEventNotificationData')(data)
  File "c:\users\buestuen2\appdata\local\continuum\anaconda3\lib\site-packages\sllurp\llrp_proto.py", line 3432, in decode_ReaderEventNotificationData
    raise LLRPError('missing or invalid UTCTimestamp parameter')
sllurp.llrp_errors.LLRPError: missing or invalid UTCTimestamp parameter
2021-03-18 19:10:05,271 sllurp.llrp: ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "c:\users\buestuen2\appdata\local\continuum\anaconda3\lib\site-packages\sllurp\llrp.py", line 126, in __repr__
    ret = llrp_data2xml(self.msgdict)
  File "c:\users\buestuen2\appdata\local\continuum\anaconda3\lib\site-packages\sllurp\llrp_proto.py", line 3864, in llrp_data2xml
    for p in msg:
TypeError: 'NoneType' object is not iterable
2021-03-18 19:10:05,272 sllurp.llrp: ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "c:\users\buestuen2\appdata\local\continuum\anaconda3\lib\site-packages\sllurp\llrp.py", line 126, in __repr__
    ret = llrp_data2xml(self.msgdict)
  File "c:\users\buestuen2\appdata\local\continuum\anaconda3\lib\site-packages\sllurp\llrp_proto.py", line 3864, in llrp_data2xml
    for p in msg:
TypeError: 'NoneType' object is not iterable
2021-03-18 19:10:05,271 sllurp.llrp: DEBUG: LLRPMessage received in state 1: 
2021-03-18 19:10:05,273 sllurp.llrp: DEBUG: starting message callbacks for None
2021-03-18 19:10:05,273 sllurp.llrp: DEBUG: done with message callbacks for None
2021-03-18 19:10:05,274 sllurp.llrp: DEBUG: in handleMessage(None), there are 0 Deferreds
2021-03-18 19:10:05,274 sllurp.llrp: ERROR: unexpected message None while connecting
2021-03-18 19:10:58,665 sllurp.llrp: INFO: stopping politely
2021-03-18 19:10:58,666 sllurp.llrp: INFO: will disconnect when stopped
2021-03-18 19:10:58,670 sllurp.llrp: DEBUG: serializing DELETE_ACCESSSPEC command
2021-03-18 19:10:58,677 sllurp.llrp: DEBUG: serialized bytes: b'04290000000e0000000100000000'
2021-03-18 19:10:58,678 sllurp.llrp: DEBUG: done serializing DELETE_ACCESSSPEC command
2021-03-18 19:10:58,681 sllurp.llrp: DEBUG: state change: STATE_DISCONNECTED -> STATE_SENT_DELETE_ACCESSSPEC
2021-03-18 19:10:58,689 sllurp.llrp: DEBUG: got 18 bytes from reader: b'04330000001200000001011f000800000000'
2021-03-18 19:10:58,690 sllurp.llrp: DEBUG: expect 18 bytes (have 18)
2021-03-18 19:10:58,692 sllurp.llrp: DEBUG: deserializing DELETE_ACCESSSPEC_RESPONSE command
2021-03-18 19:10:58,711 sllurp.llrp_proto: DEBUG: decode_DeleteROSpecResponse
2021-03-18 19:10:58,722 sllurp.llrp_proto: DEBUG: decode_LLRPStatus
2021-03-18 19:10:58,722 sllurp.llrp_proto: DEBUG: decode_LLRPStatus: b'011f000800000000'
2021-03-18 19:10:58,731 sllurp.llrp_proto: DEBUG: decode_LLRPStatus (type=287 len=8)
2021-03-18 19:10:58,738 sllurp.llrp_proto: DEBUG: decode_FieldError
2021-03-18 19:10:58,739 sllurp.llrp_proto: DEBUG: no FieldError
2021-03-18 19:10:58,745 sllurp.llrp_proto: DEBUG: decode_ParameterError
2021-03-18 19:10:58,746 sllurp.llrp_proto: DEBUG: no ParameterError
2021-03-18 19:10:58,746 sllurp.llrp: DEBUG: done deserializing DELETE_ACCESSSPEC_RESPONSE command
2021-03-18 19:10:58,747 sllurp.llrp: DEBUG: LLRPMessage received in state 20: <DELETE_ACCESSSPEC_RESPONSE>
	<Ver>1</Ver>
	<Type>51</Type>
	<ID>1</ID>
	<LLRPStatus>
		<StatusCode>'Success'</StatusCode>
		<ErrorDescription>b''</ErrorDescription>
	</LLRPStatus>
</DELETE_ACCESSSPEC_RESPONSE>
2021-03-18 19:10:58,748 sllurp.llrp: DEBUG: starting message callbacks for DELETE_ACCESSSPEC_RESPONSE
2021-03-18 19:10:58,748 sllurp.llrp: DEBUG: done with message callbacks for DELETE_ACCESSSPEC_RESPONSE
2021-03-18 19:10:58,749 sllurp.llrp: DEBUG: in handleMessage(DELETE_ACCESSSPEC_RESPONSE), there are 1 Deferreds
2021-03-18 19:10:58,751 sllurp.llrp: DEBUG: running 1 Deferreds for DELETE_ACCESSSPEC_RESPONSE; isSuccess=True
2021-03-18 19:10:58,751 sllurp.llrp: DEBUG: serializing DELETE_ROSPEC command
2021-03-18 19:10:58,752 sllurp.llrp: DEBUG: serialized bytes: b'04150000000e0000000200000000'
2021-03-18 19:10:58,752 sllurp.llrp: DEBUG: done serializing DELETE_ROSPEC command
2021-03-18 19:10:58,753 sllurp.llrp: DEBUG: state change: STATE_SENT_DELETE_ACCESSSPEC -> STATE_SENT_DELETE_ROSPEC
2021-03-18 19:10:58,755 sllurp.llrp: DEBUG: got 18 bytes from reader: b'041f0000001200000002011f000800000000'
2021-03-18 19:10:58,756 sllurp.llrp: DEBUG: expect 18 bytes (have 18)
2021-03-18 19:10:58,756 sllurp.llrp: DEBUG: deserializing DELETE_ROSPEC_RESPONSE command
2021-03-18 19:10:58,761 sllurp.llrp_proto: DEBUG: decode_DeleteROSpecResponse
2021-03-18 19:10:58,766 sllurp.llrp_proto: DEBUG: decode_LLRPStatus
2021-03-18 19:10:58,767 sllurp.llrp_proto: DEBUG: decode_LLRPStatus: b'011f000800000000'
2021-03-18 19:10:58,773 sllurp.llrp_proto: DEBUG: decode_LLRPStatus (type=287 len=8)
2021-03-18 19:10:58,779 sllurp.llrp_proto: DEBUG: decode_FieldError
2021-03-18 19:10:58,779 sllurp.llrp_proto: DEBUG: no FieldError
2021-03-18 19:10:58,786 sllurp.llrp_proto: DEBUG: decode_ParameterError
2021-03-18 19:10:58,786 sllurp.llrp_proto: DEBUG: no ParameterError
2021-03-18 19:10:58,787 sllurp.llrp: DEBUG: done deserializing DELETE_ROSPEC_RESPONSE command
2021-03-18 19:10:58,787 sllurp.llrp: DEBUG: LLRPMessage received in state 19: <DELETE_ROSPEC_RESPONSE>
	<Ver>1</Ver>
	<Type>31</Type>
	<ID>2</ID>
	<LLRPStatus>
		<StatusCode>'Success'</StatusCode>
		<ErrorDescription>b''</ErrorDescription>
	</LLRPStatus>
</DELETE_ROSPEC_RESPONSE>
2021-03-18 19:10:58,788 sllurp.llrp: DEBUG: starting message callbacks for DELETE_ROSPEC_RESPONSE
2021-03-18 19:10:58,789 sllurp.llrp: DEBUG: done with message callbacks for DELETE_ROSPEC_RESPONSE
2021-03-18 19:10:58,789 sllurp.llrp: DEBUG: in handleMessage(DELETE_ROSPEC_RESPONSE), there are 1 Deferreds
2021-03-18 19:10:58,790 sllurp.llrp: DEBUG: state change: STATE_SENT_DELETE_ROSPEC -> STATE_DISCONNECTED
2021-03-18 19:10:58,790 sllurp.llrp: DEBUG: running 1 Deferreds for DELETE_ROSPEC_RESPONSE; isSuccess=True
2021-03-18 19:10:58,791 sllurp.llrp: INFO: lost connection: Connection to the other side was lost in a non-clean fashion: Connection lost.
2021-03-18 19:10:58,791 sllurp.verb.inventory: INFO: total # of tags seen: 0 (0 tags/second)
2021-03-18 19:10:58,792 sllurp.llrp: INFO: disconnecting

**Comment by ransford** [comment]
Looks like a sllurp bug: ReaderEventNotificationData can contain either UTCTimestamp _or_ Uptime as the Timestamp parameter. Most readers send UTCTimestamp, but I guess yours doesn't!

On `develop`, I confirmed with `bin/decode 043f000000200000000000f600160081000c00000000da3c043d010000060000` that sllurp didn't know how to decode your reader's message; changing the `81` to `80` (== 128) made it happy.

I just pushed a change that makes it accept Uptime in addition to UTCTimestamp. See if that works?
