### ISSUE TITLE
TypeError: encode_AccessSpecStopTrigger() 🙏🙏🙏

### ISSUE THREAD

**Issue by Ruslanch0s** [ransford/sllurp#187]
Please help, I can't solve the problem. 🙏
This always happens when I want to change something in a shortcut.
Objective: Protect the tag from cloning using an access password so that the data cannot be read without the password.

**VERSION**: sllurp-2.0.1
**COMMAND**: sllurp access 192.168.88.252 -t 1 -r 10
**ERROR**: TypeError: encode_AccessSpecStopTrigger() takes 1 positional argument but 2 were given

```
(.venv) ➜  sllurp-2.0.1 git:(main) ✗ sllurp access 192.168.88.252 -t 1 -r 10
2024-10-02 15:35:41,418 sllurp.llrp: INFO: will reset reader state on connect
2024-10-02 15:35:41,419 sllurp.llrp: INFO: will start inventory on connect
2024-10-02 15:35:41,419 sllurp.llrp: INFO: using antennas: [0]
2024-10-02 15:35:41,419 sllurp.llrp: INFO: transmit power: {0: 0}
2024-10-02 15:35:41,428 sllurp.llrp: INFO: connected to 192.168.88.252 (:5084)
2024-10-02 15:35:41,440 sllurp.llrp: INFO: using reader mode: None
2024-10-02 15:35:41,453 sllurp.llrp: INFO: stopping politely
2024-10-02 15:35:41,469 sllurp.verb.access: INFO: no tags seen
2024-10-02 15:35:41,470 sllurp.llrp: INFO: Impinj search mode? None
2024-10-02 15:35:41,470 sllurp.llrp: INFO: starting inventory
2024-10-02 15:35:41,483 sllurp.llrp: ERROR: Error during state change callback execution. Continuing anyway...
Traceback (most recent call last):
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp.py", line 1938, in _on_llrp_state_changed
    fn(self, newstate)
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/verb/access.py", line 47, in access_cb
    return reader.start_access_spec(opspec, stop_after_count=args.count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp.py", line 1921, in start_access_spec
    self.llrp.startAccess(opSpec=op_spec,
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp.py", line 1047, in startAccess
    self.send_ADD_ACCESSSPEC(accessSpec,
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp.py", line 912, in send_ADD_ACCESSSPEC
    self.sendMessage({
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp.py", line 1360, in sendMessage
    llrp_msg = LLRPMessage(msgdict=msg_dict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp.py", line 45, in __init__
    self.serialize()
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp.py", line 78, in serialize
    data = encoder(msgitem, msg_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp_proto.py", line 612, in encode_all_parameters
    data_list.append(encode_param(key, value))
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp_proto.py", line 576, in encode_param
    sub_data = encode_func(par, param_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp_proto.py", line 1546, in encode_AccessSpec
    return encode_all_parameters(par, param_info, packed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp_proto.py", line 612, in encode_all_parameters
    data_list.append(encode_param(key, value))
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruslanch0s/PycharmProjects/rfid_reader/.venv/lib/python3.12/site-packages/sllurp/llrp_proto.py", line 576, in encode_param
    sub_data = encode_func(par, param_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: encode_AccessSpecStopTrigger() takes 1 positional argument but 2 were given
```

**Comment by fviard** [comment]
There should be a fix for this issue in Master know, don't hesitate to give it a try if you can.

**Comment by Ruslanch0s** [comment]
Thank you very much for your support
