### ISSUE TITLE
Lost Connection: Unpack requires a string argument of length 10

### ISSUE THREAD

**Issue by zkapetanovic** [ransford/sllurp#36]
A frequent error has been occurring while running sllurp and causes a connection timeout. It seems that there is an issue with unpacking data and results in the error 'unpack requires a string argument of length 10'. I'm not sure what steps to take to resolve the issue. Below is copy of the error received,

```python
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 220, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 578, in dataReceived
    why = self.rawDataReceived(data)
  File "/Users/zerina/sllurp/sllurp/llrp.py", line 508, in rawDataReceived
    data[:LLRPMessage.full_hdr_len])
struct.error: unpack requires a string argument of length 10
INFO:sllurp.llrp:lost connection: unpack requires a string argument of length 10
```

**Comment by ransford** [comment]
Is this issue still cropping up?

**Comment by zkapetanovic** [comment]
It hasn't occurred after switching to the issue36 branch, but I also
haven't ran it in a while. I'll let you know if it pops up again ...
hopefully not!

**Comment by ransford** [comment]
I'm going to close this since it looks like there was a solution (long since merged into `master`).
