### ISSUE TITLE
Errors while running `bin/access`

### ISSUE THREAD

**Issue by ivarveen** [ransford/sllurp#37]
When running the access script I encounter two errors:

The first is right at the start of the script (using the `-r 1` argument):
```python
2015-01-12 16:11:46,668 sllurp.llrp: ERROR: panic(): ('ENABLE_ROSPEC failed',)
2015-01-12 16:11:46,669 sllurp.llrp: ERROR: 'int' object has no attribute '__getitem__'
2015-01-12 16:11:46,669 sllurp.llrp: ERROR: Traceback (most recent call last):
  File "sllurp/llrp.py", line 440, in handleMessage
    self.processDeferreds(msgName, lmsg.isSuccess())
  File "sllurp/llrp.py", line 301, in processDeferreds
    d.callback(self.state)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "sllurp/llrp.py", line 232, in _setState_wrapper
    self.setState(args[0], **kwargs)
  File "sllurp/llrp.py", line 227, in setState
    fn(self)
  File "/home/ivar/Code/sllurp/sllurp/access.py", line 21, in access
    writeWords=args.write_words)
  File "sllurp/llrp.py", line 611, in startAccess
    opSpecParam['MB'] = readWords['MB']
exceptions.TypeError: 'int' object has no attribute '__getitem__'
```

The second error is right before the end of the program:
```python
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1085, in connectionLost
    self.factory.clientConnectionLost(self, reason)
  File "sllurp/llrp.py", line 842, in clientConnectionLost
    self.onFinish.callback(None)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/ivar/Code/sllurp/sllurp/access.py", line 17, in finish
    reactor.stop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 580, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```

I'll create a PR fixing these.

**Comment by ransford** [comment]
Closed by #38.
