### ISSUE TITLE
Error with Reader API

### ISSUE THREAD

**Issue by farisshajahan** [ransford/sllurp#83]
I tried using your Reader API given in the README exactly as it is in a test.py file

test.py:

```
from sllurp import llrp
from twisted.internet import reactor
import logging
logging.getLogger().setLevel(logging.INFO)

def cb (tagReport):
    tags = tagReport.msgdict['RO_ACCESS_REPORT']['TagReportData']
    print 'tags:', tags

factory = llrp.LLRPClientFactory()
factory.addTagReportCallback(cb)
reactor.connectTCP('readerIP', llrp.LLRP_PORT, factory)
reactor.run()
```

and ran it with `python test.py`

But it gives some key errors

```
Unhandled Error
Traceback (most recent call last):
  File "/home/dladmin/test/.venv/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/dladmin/test/.venv/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/dladmin/test/.venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/dladmin/test/.venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/dladmin/test/.venv/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
    why = selectable.doWrite()
  File "/home/dladmin/test/.venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 583, in doConnect
    self._connectDone()
  File "/home/dladmin/test/.venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 597, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/home/dladmin/test/.venv/lib/python3.5/site-packages/twisted/internet/base.py", line 1140, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "/home/dladmin/test/sllurp/sllurp/llrp.py", line 1256, in buildProtocol
    clargs['start_inventory'])
builtins.KeyError: 'start_inventory'
```

**Comment by ransford** [comment]
Try checking out the latest `develop`, where I closed this in 2a28d6b9ccd36be964bf1bc4925dae5e897032ba.  Fix will go into the next release.
